sources:
  - name: FangornMusic
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/1745244/fangorn-data-discovery/version/latest

documents:
  - ./src/renderer/src/queries/*.graphql

generates:
  - ./src/.graphclient